# Read the Docs configuration for the Windows ML subproject.
# Set "Path for .readthedocs.yaml" in RTD project settings to:
#   docs/winml/.readthedocs.yaml

version: 2

sphinx:
   configuration: docs/winml/conf.py

formats: [htmlzip, pdf, epub]

python:
   install:
   - requirements: docs/sphinx/requirements.txt

build:
   os: ubuntu-22.04
   tools:
      python: "3.10"
